-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 12:13:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booking` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `booking` ;

-- -----------------------------------------------------
-- Table `booking`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM('client', 'administrator') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`FundBlock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`FundBlock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `block_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `block_date` DATE NULL DEFAULT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_FundBlock_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_FundBlock_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`HotelChain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`HotelChain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`Hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `contact_info` VARCHAR(225) NULL DEFAULT NULL,
  `rating` DECIMAL(3,2) NULL DEFAULT NULL,
  `HotelChain_id` INT NOT NULL,
  PRIMARY KEY (`id`, `HotelChain_id`),
  INDEX `fk_Hotel_HotelChain1_idx` (`HotelChain_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_HotelChain1`
    FOREIGN KEY (`HotelChain_id`)
    REFERENCES `booking`.`HotelChain` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`HotelLocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`HotelLocation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(55) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `Hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Hotel_id`),
  INDEX `fk_HotelLocation_Hotel1_idx` (`Hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_HotelLocation_Hotel1`
    FOREIGN KEY (`Hotel_id`)
    REFERENCES `booking`.`Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`RegistrationConfirmation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`RegistrationConfirmation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `send_date` DATE NULL DEFAULT NULL,
  `status` ENUM('confirmed', 'pending') NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_RegistrationConfirmation_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_RegistrationConfirmation_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`Room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NULL DEFAULT NULL,
  `price_per_night` DECIMAL(10,2) NULL DEFAULT NULL,
  `availability` TINYINT NULL DEFAULT NULL,
  `Hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Hotel_id`),
  INDEX `fk_Room_Hotel1_idx` (`Hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_Room_Hotel1`
    FOREIGN KEY (`Hotel_id`)
    REFERENCES `booking`.`Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`Reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `status` ENUM('confirmed', 'pending') NOT NULL,
  `User_id` INT NOT NULL,
  `Room_id` INT NOT NULL,
  `FundBlock_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`, `Room_id`, `FundBlock_id`),
  INDEX `fk_Reservation_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Reservation_Room1_idx` (`Room_id` ASC) VISIBLE,
  INDEX `fk_Reservation_FundBlock1_idx` (`FundBlock_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Room1`
    FOREIGN KEY (`Room_id`)
    REFERENCES `booking`.`Room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_FundBlock1`
    FOREIGN KEY (`FundBlock_id`)
    REFERENCES `booking`.`FundBlock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `booking`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`Review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review_text` VARCHAR(1000) NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `User_id` INT NOT NULL,
  `Hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Hotel_id`, `User_id`),
  INDEX `fk_Review_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Review_Hotel1_idx` (`Hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `booking`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Hotel1`
    FOREIGN KEY (`Hotel_id`)
    REFERENCES `booking`.`Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Hotel (name, address, contact_info, rating, hotelchain_id)
VALUES
    ('Dnipro', 'Wall Street 3', '+18882901046', 4.5, 1),
    ('Dnister', 'Baker Street 102', '+447156197685', 3.8, 1),
    ('Danube', 'Beverly Hills 23', '+18887991072', 2.8, 1),
    ('Desna', 'Krupiarska 1', '+380680781956', 3.8, 1),
    ('Stryi', 'Harelbeekstraat 6', '+32487894373', 4.2, 1);

INSERT INTO HotelLocation (country, city, Hotel_id)
VALUES
    ('USA', 'New York', 1),
    ('UK', 'London', 2),
    ('USA', 'Los Angeles', 3),
    ('Ukraine', 'Lviv', 4),
    ('Belgium', 'Kortrijk', 5);
    
INSERT INTO Room (room_type, price_per_night, availability, hotel_id)
VALUES
    ('Single', 100.00, 1, 1),
    ('Double', 200.00, 1, 1),
    ('Triple', 200.00, 0, 1),
    ('Queen', 200.00, 0, 1),
    ('King', 150.00, 1, 1);

INSERT INTO User (name, email, password, role)
VALUES
    ('Sigma', 'sigma@gmail.com', 'roman12345', 'client'),
    ('Miwa', 'anna@gmail.com', 'efwfe22e2', 'client'),
    ('Danko', 'anna@gmail.com', 'fe1fefwqq2q', 'client'),
    ('Amor', 'anna@gmail.com', '9iuiu2iy', 'client'),
    ('Andryi', 'adriqy@gmail.com', 'rtyui22', 'administrator');
    
INSERT INTO Review (user_id, hotel_id, review_text, rating)
VALUES
    (1, 1, 'The staff was great. The receptionists were very helpful and answered all our questions.', 5),
    (2, 1, 'The hotel’s elegant design, combined with its top-notch amenities.', 4),
    (3, 2, 'The food was fresh and delicious, and the best part was that the chef sent us a dessert they had created that day.', 5),
    (4, 2, 'It’s truly a game-changer and a must-have app for anyone looking to improve their overall digital experience..', 3),
    (5, 5, 'The entire team provided outstanding care and support, making my journey a positive and empowering experience. .', 4);
    
INSERT INTO FundBlock (user_id, block_amount, block_date)
VALUES
    (1, 200.00, '2023-09-20'),
    (2, 180.00, '2023-09-22'),
    (3, 150.00, '2023-09-24'),
    (4, 220.00, '2023-09-26'),
    (5, 210.00, '2023-09-28');
    
INSERT INTO Reservation (user_id, room_id, start_date, end_date, status, fundblock_id)
VALUES
    (1, 1, '2023-09-20', '2023-09-25', 'pending', 1),
    (2, 1, '2023-09-22', '2023-09-27', 'confirmed', 1),
    (3, 2, '2023-09-24', '2023-09-29', 'pending', 1),
    (4, 3, '2023-09-26', '2023-09-30', 'confirmed', 1),
    (5, 5, '2023-09-28', '2023-10-02', 'pending', 1);
    
INSERT INTO RegistrationConfirmation (user_id, send_date, status)
VALUES
    (1, '2023-09-05', 'pending'),
    (2, '2023-09-07', 'pending'),
    (3, '2023-09-10', 'confirmed'),
    (4, '2023-09-12', 'pending'),
    (5, '2023-09-15', 'confirmed');

INSERT INTO HotelChain (name)
VALUES
    ('Buckingham'),
    ('LA'),
    ('Noret'),
    ('Yean'),
    ('Pak');


